on:
  push:
    # Sequence of patterns matched against refs/tags - this will be handy in an acy=tual working enviroment, where we can specify what needs a release and what does not
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload Static
        uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/