name: Upload Release Asset
on:
  push:
    # Sequence of patterns matched against refs/tags - this will be handy in an acy=tual working enviroment, where we can specify what needs a release and what does not
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build & Upload Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
	uses: npm install
      - name: Build source code
	uses: npm run build
      - name: Upload Artefact
	uses: actions/upload-artifact@v2
	with:
	  name: X's&O's
	  path: out\
      